version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    reviewers:
      - "daht-x"
    assignees:
      - "daht-x"
    commit-message:
      prefix: "dependency"
    labels:
      - "scope: root"
      - "topic: dependency"
      - "package manager: github actions"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    reviewers:
      - "daht-x"
    assignees:
      - "daht-x"
    allow:
      - dependency-name: "@commitlint/cli"
      - dependency-name: "@eslint/js"
      - dependency-name: "eslint"
      - dependency-name: "eslint-config-airbnb-base"
      - dependency-name: "eslint-config-prettier"
      - dependency-name: "eslint-plugin-import"
      - dependency-name: "husky"
      - dependency-name: "lint-staged"
      - dependency-name: "markdown-link-check"
      - dependency-name: "markdownlint-cli"
      - dependency-name: "prettier"
    commit-message:
      prefix: "dependency"
    labels:
      - "scope: root"
      - "topic: dependency"
      - "package manager: pnpm"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    target-branch: "main"
    directory: "/"
    reviewers:
      - "daht-x"
    assignees:
      - "daht-x"
    allow:
      - dependency-name: "SonarAnalyzer.CSharp"
    commit-message:
      prefix: "dependency"
    labels:
      - "scope: root"
      - "topic: dependency"
      - "package manager: nuget"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
