version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    assignees:
      - "daht-x"
    commit-message:
      prefix: "dependency"
    labels:
      - "topic: dependency"
      - "package manager: github actions"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/"
    assignees:
      - "daht-x"
    commit-message:
      prefix: "dependency"
    labels:
      - "topic: dependency"
      - "package manager: pnpm"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    target-branch: "main"
    directory: "/"
    assignees:
      - "daht-x"
    commit-message:
      prefix: "dependency"
    labels:
      - "topic: dependency"
      - "package manager: nuget"
      - "priority: medium"
      - "status: pending"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
