changelog:
  exclude:
    authors:
      - "dependabot"
  categories:
    - title: "Build system"
      labels:
        - "topic: build"
    - title: "Bug fixes"
      labels:
        - "topic: bug"
    - title: "New features and enhancements"
      labels:
        - "topic: feature"
    - title: "Dependencies management"
      labels:
        - "package manager: nuget"
      exclude:
        labels:
          - "package manager: github actions"
          - "package manager: pnpm"
