changelog:
  exclude:
    authors:
      - "dependabot"
  categories:
    - title: "Compatibility"
      labels:
        - "topic: compatibility"
    - title: "Build system"
      labels:
        - "topic: build"
    - title: "Bug fixes"
      labels:
        - "topic: bug"
    - title: "New features and enhancements"
      labels:
        - "topic: feature"
