extends: "default"
locale: "en_US.UTF-8"
yaml-files:
  - "*.yaml"
  - "*.yml"
ignore:
  - "pnpm-lock.yaml"
rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true
  braces:
    forbid: true
  brackets:
    forbid: true
  comments-indentation: "enable"
  document-start:
    present: false
  empty-lines:
    max: 0
  float-values:
    require-numeral-before-decimal: true
  indentation:
    spaces: 2
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
    required: true
  truthy:
    allowed-values:
      - "true"
      - "false"
      - "on"
