name: "Bug report"
description: "Report a bug or unintended behavior."
assignees: "daht-x"
labels:
  - "topic: bug"
  - "priority: high"
  - "status: pending"
body:
  - type: "markdown"
    attributes:
      value: "***Thank you very much for your contribution***"
  - type: "markdown"
    attributes:
      value: "Please read and follow our [code of conduct](https://github.com/daht-x/sagitta-core/blob/main/code-of-conduct.md) and [contributing guidelines](https://github.com/daht-x/sagitta-core/blob/main/contributing.md)."
  - type: "textarea"
    id: "description"
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Provide a clear and concise description of the issue."
  - type: "textarea"
    id: "replication"
    validations:
      required: true
    attributes:
      label: "Replication"
      description: "Provide a set of minimal steps to replicate the issue."
  - type: "textarea"
    id: "expected-behavior"
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "Provide a description of the expected behavior."
  - type: "textarea"
    id: "actual-behavior"
    validations:
      required: true
    attributes:
      label: "Actual behavior"
      description: "Provide a description of the actual behavior."
  - type: "textarea"
    id: "additional-information"
    validations:
      required: false
    attributes:
      label: "Additional information"
      description: "Provide related issues, relevant changes, suggestions, etc."
