#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
run() {
	dotnet clean
	dotnet restore
	local build_configuration='Release'
	readonly build_configuration
	dotnet build \
		--no-restore \
		--configuration "$build_configuration"
	dotnet test \
		--no-build \
		--configuration "$build_configuration"
	exit 0
}
run
