#!/usr/bin/env bash

set -o 'errexit'
set -o 'nounset'
set -o 'pipefail'
run() {
	trufflehog git 'file://.' \
		--trust-local-git-config \
		--since-commit 'HEAD' \
		--results 'verified,unknown' \
		--fail
	lint-staged --relative
	exit $?
}
run
