#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"
dotnet clean
dotnet restore
buildConfiguration='Release'
dotnet build \
	--no-restore \
	--configuration "$buildConfiguration"
dotnet test \
	--no-build \
	--configuration "$buildConfiguration"
