name: "Documentation"
on:
  pull_request:
    paths:
      - "**.md"
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
env:
  SEARCH_PATTERN: "**.md"
jobs:
  linter:
    name: "Linter"
    if: "${{ github.event_name == 'pull_request' }}"
    runs-on: "${{ vars.DEFAULT_UBUNTU }}"
    steps:
      - name: "Set up repository with all history"
        uses: "actions/checkout@v4.1.1"
        with:
          fetch-depth: 0
      - name: "Get all changed files"
        id: "changed-files"
        uses: "tj-actions/changed-files@v40.1.1"
        with:
          files: "${{ env.SEARCH_PATTERN }}"
      - name: "Run linter for all changed files"
        uses: "DavidAnson/markdownlint-cli2-action@v13.0.0"
        with:
          globs: "${{ steps.changed-files.outputs.all_changed_files }}"
  link-checker:
    name: "Link checker"
    runs-on: "${{ vars.DEFAULT_UBUNTU }}"
    env:
      IS_PULL_REQUEST_EVENT: "${{ github.event_name == 'pull_request' }}"
      IS_SCHEDULE_OR_WORKFLOW_DISPATCH_EVENT: "${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}"
      POSITIVE_RESPONSE: "true"
      MARKDOWN_LINK_CHECK_FILE: ".markdownlc.json"
    steps:
      - name: "Set up workspace"
        if: "${{ env.IS_PULL_REQUEST_EVENT == env.POSITIVE_RESPONSE }}"
        uses: "actions/checkout@v4.1.1"
      - name: "Set up workspace"
        if: "${{ env.IS_SCHEDULE_OR_WORKFLOW_DISPATCH_EVENT == env.POSITIVE_RESPONSE }}"
        uses: "actions/checkout@v4.1.1"
        with:
          fetch-depth: 0
      - name: "Run link checker"
        if: "${{ env.IS_PULL_REQUEST_EVENT == env.POSITIVE_RESPONSE }}"
        uses: "gaurav-nelson/github-action-markdown-link-check@1.0.15"
        with:
          base-branch: "${{ github.ref_name }}"
          check-modified-files-only: true
          use-quiet-mode: true
          config-file: "${{ env.MARKDOWN_LINK_CHECK_FILE }}"
      - name: "Run link checker"
        if: "${{ env.IS_SCHEDULE_OR_WORKFLOW_DISPATCH_EVENT == env.POSITIVE_RESPONSE }}"
        uses: "gaurav-nelson/github-action-markdown-link-check@1.0.15"
        with:
          base-branch: "${{ github.ref_name }}"
          use-quiet-mode: true
          config-file: "${{ env.MARKDOWN_LINK_CHECK_FILE }}"
