name: "Documentation"
on:
  push:
    branches:
      - "main"
    paths:
      - "**.md"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.md"
  schedule:
    - cron: "0 8 */2 * *"
  workflow_dispatch:
jobs:
  redundancy:
    name: "Redundancy"
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Cancel previous workflow runs"
        uses: "styfle/cancel-workflow-action@0.11.0"
        with:
          all_but_latest: true
          access_token: "${{ github.token }}"
  consistency:
    name: "Consistency"
    env:
      MARKDOWN_LINK_CHECK_CONFIGURATION_FILE: ".markdownlc.json"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up workspace (applicable to last commit)"
        if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' }}"
        uses: "actions/checkout@v4.1.0"
      - name: "Set up workspace (applicable to all commits)"
        if: "${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}"
        uses: "actions/checkout@v4.1.0"
        with:
          fetch-depth: 0
      - name: "Check the rules of the static analyzer"
        if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' }}"
        uses: "avto-dev/markdown-lint@v1.5.0"
        with:
          args: "**.md"
      - name: "Check the status of hyperlinks (applicable to all modified files)"
        if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' }}"
        uses: "gaurav-nelson/github-action-markdown-link-check@1.0.15"
        with:
          base-branch: "main"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          config-file: "${{ env.MARKDOWN_LINK_CHECK_CONFIGURATION_FILE }}"
      - name: "Check the status of hyperlinks (applicable to all files)"
        if: "${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}"
        uses: "gaurav-nelson/github-action-markdown-link-check@1.0.15"
        with:
          base-branch: "main"
          use-quiet-mode: "yes"
          config-file: "${{ env.MARKDOWN_LINK_CHECK_CONFIGURATION_FILE }}"
