name: "TypeScript"
on:
  push:
    branches:
      - "main"
    paths:
      - "**.ts"
  pull_request:
    paths:
      - "**.ts"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
env:
  SEARCH_PATTERN: "**.ts"
jobs:
  formatter:
    name: "Formatter"
    runs-on: "${{ vars.DEFAULT_UBUNTU }}"
    steps:
      - name: "Set up repository with all history"
        uses: "actions/checkout@v4.2.2"
        with:
          fetch-depth: 0
      - name: "Get all changed files"
        id: "typescript-files"
        uses: "tj-actions/changed-files@v45.0.7"
        with:
          files: "${{ env.SEARCH_PATTERN }}"
      - name: "Set up formatter"
        uses: "biomejs/setup-biome@v2.3.0"
      - name: "Run formatter for all changed files"
        run: "biome format ${{ steps.typescript-files.outputs.all_changed_files }}"
  linter:
    name: "Linter"
    runs-on: "${{ vars.DEFAULT_UBUNTU }}"
    steps:
      - name: "Set up repository with all history"
        uses: "actions/checkout@v4.2.2"
        with:
          fetch-depth: 0
      - name: "Get all changed files"
        id: "typescript-files"
        uses: "tj-actions/changed-files@v45.0.7"
        with:
          files: "${{ env.SEARCH_PATTERN }}"
      - name: "Set up linter"
        uses: "biomejs/setup-biome@v2.3.0"
      - name: "Run linter for all changed files"
        run: "biome lint ${{ steps.typescript-files.outputs.all_changed_files }}"
